---
slug: jekyll-book
filename: jekyll-book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2015
uuid: f2fc2231-9659-40ab-86da-e72c501ada77
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
